[[memory-consistency]]
== Vector Memory Consistency Model

Vector memory instructions appear to execute in program order on the
local hart.

Vector memory instructions follow RVWMO at the instruction level.

Except for vector indexed-ordered loads and stores, element operations
are unordered within the instruction.

Vector indexed-ordered loads and stores read and write elements
from/to memory in element order respectively.

NOTE: More formal definitions required.

Instructions affected by the vector length register `vl` have a control
dependency on `vl`, rather than a data dependency.
Similarly, masked vector instructions have a control dependency on the source
mask register, rather than a data dependency.

NOTE: Treating the vector length and mask as control rather than data
typically matches the semantics of the corresponding scalar code, where branch
instructions ordinarily would have been used.
Treating the mask as control allows masked vector load instructions to access
memory before the mask value is known, without the need for
a misspeculation-recovery mechanism.
